### ISSUE TITLE
[Add Check]: video files linked to nwbfiles via the external_files argument

### ISSUE THREAD

**Issue by Saksham20** [catalystneuro/nwbinspector#24]
### What would you like to see added to the NWBInspector?

Since video files are linked to nwbfiles with the `external_file` attribute, I think we can do some basic validation of these that can go in the core:
- whether the video path under `external_file` exists at all(high importance of warning)
- video is of commonly found file extensions: .mp4, .avi, .mov, .wmv, .flv (lowest importance)
- whether the path specified is a relative path (w.r.t the nwbfile) or an absolute path. (low importance)

### Do you have any interest in helping implement the check function?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
For starters, I think we can extend a couple of these checks to any object that uses external links.

> whether the video path under external_file exists at all(high importance of warning)

Yeah, that would be great for any object that can and does have external links specified.

> whether the path specified is a relative path (w.r.t the nwbfile) or an absolute path. (low importance)

Similar to the above, this would also be good to check for any external link. The reasoning of course is that for (a) cross-platform sharing of NWBFiles the first few fields of any absolute path will differ, (b) If the nesting of the absolute path is somewhat deep and specific, even users on the same platform will encounter issues from folder discrepancies, and finally (c) DANDI will outright require this.

> video is of commonly found file extensions: .mp4, .avi, .mov, .wmv, .flv (lowest importance)

This is the only one specific to `ImageSeries`, however, I do think the core checks here on NWBInspector should be the most generous we can possibly be (i.e., any video format that can be opened by any external video viewer). Can you compile a list of all such suffixes? Note that I do not refer here only to the ones openable by OpenCV or other tools.
